fix: Add `spec` parameter to `MagicMock` constructors and update `team_permission` attribute
Tests for `update_repo_by_id` generate the following error:
`AttributeError: 'TeamPermission' object has no attribute 'permission'.`

Truly, `permission` attribute doesn't exist, but tests in `test_access_control.py` are successful. This is because `spec=Repository` is not used in the `MagicMock` constructor for the `repo` variable in `test_access_control.py`. Consequently, without this, any attribute can be defined.

I have updated all potentially problematic constructors to address this issue.